// Extracts game data from the GPL Digger Remastered reference source into
// TypeScript modules under src/assets/. Run via `npm run extract` after
// cloning the reference repos:
//   reference/digger-jenner   https://github.com/davecahill/digger
//   reference/digger-sobomax  https://github.com/sobomax/digger
//
// All extracted data is Copyright (c) Andrew Jenner 1998-2004, GPL v2.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const jenner = (f) => join(root, 'reference', 'digger-jenner', f);
const sobomax = (f) => join(root, 'reference', 'digger-sobomax', f);
const outDir = join(root, 'src', 'assets');
mkdirSync(outDir, { recursive: true });

const stripComments = (s) => s.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');

// Parse every `[static] [const] (u)intN_t [near] name[...] = { numbers };`
function parseNumberArrays(src) {
  const out = new Map();
  const re = /(?:static\s+)?(?:const\s+)?u?int(?:8|16)_t\s+(?:near\s+)?(\w+)\s*\[[^\]]*\]\s*=\s*\{([^{}]*)\}/g;
  let m;
  while ((m = re.exec(src)) !== null) {
    const vals = m[2]
      .split(',')
      .map((t) => t.trim())
      .filter((t) => t.length > 0)
      .map((t) => {
        const n = Number(t);
        if (!Number.isInteger(n)) throw new Error(`bad value '${t}' in ${m[1]}`);
        return n;
      });
    out.set(m[1], vals);
  }
  return out;
}

// Parse a pointer table `... *name[...] = { ident, 0, ident, ... };` → identifiers (null for 0)
function parsePtrTable(src, name) {
  const re = new RegExp(`\\*\\s*${name}\\s*\\[[^\\]]*\\]\\s*=\\s*\\{([^{}]*)\\}`);
  const m = src.match(re);
  if (!m) throw new Error(`pointer table ${name} not found`);
  return m[1]
    .split(',')
    .map((t) => t.trim())
    .filter((t) => t.length > 0)
    .map((t) => (t === '0' ? null : t));
}

const b64 = (vals) => Buffer.from(Uint8Array.from(vals)).toString('base64');

const header = (what, src) => `// GENERATED by tools/extract/extract.mjs — do not edit by hand.
// ${what}, extracted from ${src} of Digger Remastered.
// Copyright (c) Andrew Jenner 1998-2004. License: GNU GPL v2 (see LICENSE).

`;

// ---------------------------------------------------------------- sprites ---
{
  const src = stripComments(readFileSync(sobomax('cgagrafx.c'), 'utf8'));
  const arrays = parseNumberArrays(src);
  const table = parsePtrTable(src, 'cgatable');
  if (table.length % 2 !== 0) throw new Error('cgatable should be (data,mask) pairs');

  // Deduplicate: emit each named array once, sprite table refers by name.
  const used = new Set(table.filter(Boolean));
  let ts = header('CGA sprite bitmaps (2bpp) and the sprite (data,mask) index table', 'cgagrafx.c');
  ts += `import { decode } from './b64';\n\n`;
  for (const name of used) {
    if (!arrays.has(name)) throw new Error(`cgatable references unknown array ${name}`);
    ts += `const ${name} = decode('${b64(arrays.get(name))}');\n`;
  }
  ts += `\nexport interface SpriteImage {\n  data: Uint8Array;\n  mask: Uint8Array;\n}\n\n`;
  ts += `export const cgaSprites: SpriteImage[] = [\n`;
  for (let i = 0; i < table.length; i += 2) {
    ts += `  { data: ${table[i]}, mask: ${table[i + 1]} }, // ${i / 2}\n`;
  }
  ts += `];\n`;
  writeFileSync(join(outDir, 'sprites.ts'), ts);
  console.log(`sprites.ts: ${table.length / 2} sprites, ${used.size} unique bitmaps`);
}

// ------------------------------------------------------------------- font ---
{
  const src = stripComments(readFileSync(jenner('alpha.c'), 'utf8'));
  const arrays = parseNumberArrays(src);
  const table = parsePtrTable(src, 'ascii2cga'); // 0x5f entries for chars 0x20..0x7e
  const used = new Set(table.filter(Boolean));
  let ts = header('CGA bitmap font glyphs (2bpp, 12x10) indexed by ASCII-0x20', 'alpha.c');
  ts += `import { decode } from './b64';\n\n`;
  for (const name of used) {
    if (!arrays.has(name)) throw new Error(`ascii2cga references unknown glyph ${name}`);
    ts += `const ${name} = decode('${b64(arrays.get(name))}');\n`;
  }
  ts += `\nexport const cgaFont: (Uint8Array | null)[] = [\n`;
  for (const name of table) ts += `  ${name ?? 'null'},\n`;
  ts += `];\n`;
  writeFileSync(join(outDir, 'font.ts'), ts);
  console.log(`font.ts: ${table.length} chars, ${used.size} glyphs`);
}

// ----------------------------------------------------------------- levels ---
{
  const src = readFileSync(jenner('main.c'), 'utf8');
  const m = src.match(/leveldat\[8\]\[MHEIGHT\]\[MWIDTH\]=\s*\{([\s\S]*?)\};/);
  if (!m) throw new Error('leveldat not found in main.c');
  const rows = [...m[1].matchAll(/"([^"]*)"/g)].map((r) => r[1]);
  if (rows.length !== 80) throw new Error(`expected 80 level rows, got ${rows.length}`);
  const levels = [];
  for (let i = 0; i < 8; i++) levels.push(rows.slice(i * 10, i * 10 + 10));
  let ts = header('The 8 level layouts (15x10 chars: S=start H=h-tunnel V=v-tunnel C=diamond B=bag)', 'main.c');
  ts += `export const levelData: string[][] = ${JSON.stringify(levels, null, 2)};\n`;
  writeFileSync(join(outDir, 'levels.ts'), ts);
  console.log(`levels.ts: ${levels.length} levels`);
}

// ------------------------------------------------------------------ music ---
{
  const src = stripComments(readFileSync(jenner('sound.c'), 'utf8'));
  const arrays = parseNumberArrays(src);
  const tunes = ['newlevjingle', 'bonusjingle', 'backgjingle', 'dirge'];
  let ts = header(
    'Music note tables: (PIT divisor, duration) pairs, 0x7d64 = end, 0x7d00 = rest. Hz = 1193181 / divisor',
    'sound.c'
  );
  for (const t of tunes) {
    if (!arrays.has(t)) throw new Error(`tune ${t} not found in sound.c`);
    ts += `export const ${t}: number[] = [${arrays.get(t).map((v) => '0x' + v.toString(16)).join(', ')}];\n`;
  }
  writeFileSync(join(outDir, 'music.ts'), ts);
  console.log(`music.ts: ${tunes.map((t) => `${t}[${arrays.get(t).length}]`).join(', ')}`);
}

console.log('done');
