// GENERATED by tools/extract/extract.mjs — do not edit by hand.
// CGA bitmap font glyphs (2bpp, 12x10) indexed by ASCII-0x20, extracted from alpha.c of Digger Remastered.
// Copyright (c) Andrew Jenner 1998-2004. License: GNU GPL v2 (see LICENSE).

import { decode } from './b64';

const cgasymspace = decode('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
const cgasymdot = decode('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAA8AA');
const cganum0 = decode('P//A///w8ADw8ADw8ADw8A/w8A/w8A/w8A/w8A/w///wP//A');
const cganum1 = decode('ADwAADwAADwAADwAADwAAPwAAPwAAPwAAPwAAPwAAPwAAPwA');
const cganum2 = decode('P//A///w8ADwAADwAADwAADwP//w///A/wAA/wAA///wP//w');
const cganum3 = decode('P/wA//8A8A8A8A8AAA8AD//AD//wAAPw8APw8APw///wP//A');
const cganum4 = decode('8AAA8AAA8A8A8A8A8A8A8A8A8A8A///wP//wAD8AAD8AAD8A');
const cganum5 = decode('P/8A//8A8AAA8AAA8AAA///AP//wAA/w8A/w8A/w///wP//A');
const cganum6 = decode('P//A///w8ADw8ADw8AAA///A///w8A/w8A/w8A/w///wP//A');
const cganum7 = decode('P//AP//wAADwAADwAADwAADwAAPwAAPwAAPwAAPwAAPwAAPw');
const cganum8 = decode('A/8AD//ADwPADwPADwPAD//AP//w8APw8APw8APw///wP//A');
const cganum9 = decode('P//A///w8ADw8ADw8ADw///wP//wAA/wAA/wAA/wAA/wAA/w');
const cgasymcolon = decode('AAAAAAAAAAAAA8AAA8AAAAAAAAAAAAAAAAAAAAAAA8AAA8AA');
const cgaletA = decode('D/8AP//APAPAPAPAPAPAP//A///w/ADw/ADw/ADw/ADw/ADw');
const cgaletB = decode('P/wA//8A8A8A8A8A8A8A//8A///w/ADw/ADw/ADw///wP//A');
const cgaletC = decode('P//A///w8ADw8ADw8AAA/AAA/AAA/AAA/ADw/ADw///wP//A');
const cgaletD = decode('///A///w8ADw8ADw8ADw8ADw/wDw/wDw/wDw/wDw///w///A');
const cgaletE = decode('P//w///w8AAA8AAA8AAA//8A//8A/wAA/wAA/wAA///wP//w');
const cgaletF = decode('P//w///w/AAA/AAA/AAA//8A//8A/wAA/wAA/wAA/wAA/wAA');
const cgaletG = decode('P//A///w8ADw8ADw8AAA8AAA/A/A/w/w/wDw/wDw///wP//A');
const cgaletH = decode('8ADw8ADw8ADw8ADw8ADw///w///w/wDw/wDw/wDw/wDw/wDw');
const cgaletI = decode('APAAAPAAAPAAAPAAAPAAAPAAAP8AAP8AAP8AAP8AAP8AAP8A');
const cgaletJ = decode('AA8AAA8AAA8AAA8AAA8AAA/wAA/w8A/w8A/w8A/w///wP//A');
const cgaletK = decode('8A8A8A8A8A8A8A8A8A8A//8A///w/wDw/wDw/wDw/wDw/wDw');
const cgaletL = decode('8AAA8AAA8AAA8AAA8AAA/wAA/wAA/wAA/wAA/wAA///wP//w');
const cgaletM = decode('P//A///w8PDw8PDw8PDw8PDw/PDw/PDw/PDw/PDw/PDw/PDw');
const cgaletN = decode('D//AP//wPADwPADwPADwPADwPwDwPwDwPwDwPwDwPwDwPwDw');
const cgaletO = decode('P//A///w8A/w8A/w8ADw8ADw8ADw8ADw8ADw8ADw///wP//A');
const cgaletP = decode('P//A///w8ADw8ADw8ADw///w///A/wAA/wAA/wAA/wAA/wAA');
const cgaletQ = decode('P//A///w8ADw8ADw8ADw8ADw8ADw8ADw8D/w8D/w///wP//A');
const cgaletR = decode('P/wA//8A8A8A8A8A8A8A//8A///w8ADw8ADw8ADw8ADw8ADw');
const cgaletS = decode('P//A///w8ADw8AAA8AAA///AP//wAA/wAA/w8A/w///wP//A');
const cgaletT = decode('///w///wAPAAAPAAAPAAAPAAAP8AAP8AAP8AAP8AAP8AAP8A');
const cgaletU = decode('8ADw8ADw8ADw8ADw8ADw/wDw/wDw/wDw/wDw/wDw///wP//A');
const cgaletV = decode('8ADw8ADw8ADw8ADw8ADw8ADw8ADw8ADwPA8APA8AP/8AD/wA');
const cgaletW = decode('8PDw8PDw8PDw8PDw8PDw8PDw/PDw/PDw/PDw/PDw///wP//A');
const cgaletX = decode('8ADw8ADw8ADw8ADw8ADwD/8AD/8A/wDw/wDw/wDw/wDw/wDw');
const cgaletY = decode('8ADw8ADw8ADw8ADw8ADw///wP//AAPwAAPwAAPwAAPwAAPwA');
const cgaletZ = decode('P//A///w8ADwAADwAADwP//w///A/wAA/wAA/wDw///wP//A');
const cgasymline = decode('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//w');

export const cgaFont: (Uint8Array | null)[] = [
  cgasymspace,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  cgasymdot,
  null,
  cganum0,
  cganum1,
  cganum2,
  cganum3,
  cganum4,
  cganum5,
  cganum6,
  cganum7,
  cganum8,
  cganum9,
  cgasymcolon,
  null,
  null,
  null,
  null,
  null,
  null,
  cgaletA,
  cgaletB,
  cgaletC,
  cgaletD,
  cgaletE,
  cgaletF,
  cgaletG,
  cgaletH,
  cgaletI,
  cgaletJ,
  cgaletK,
  cgaletL,
  cgaletM,
  cgaletN,
  cgaletO,
  cgaletP,
  cgaletQ,
  cgaletR,
  cgaletS,
  cgaletT,
  cgaletU,
  cgaletV,
  cgaletW,
  cgaletX,
  cgaletY,
  cgaletZ,
  null,
  null,
  null,
  null,
  cgasymline,
  null,
  cgaletA,
  cgaletB,
  cgaletC,
  cgaletD,
  cgaletE,
  cgaletF,
  cgaletG,
  cgaletH,
  cgaletI,
  cgaletJ,
  cgaletK,
  cgaletL,
  cgaletM,
  cgaletN,
  cgaletO,
  cgaletP,
  cgaletQ,
  cgaletR,
  cgaletS,
  cgaletT,
  cgaletU,
  cgaletV,
  cgaletW,
  cgaletX,
  cgaletY,
  cgaletZ,
  null,
  null,
  null,
  null,
];
