// GENERATED by tools/extract/extract.mjs — do not edit by hand.
// CGA sprite bitmaps (2bpp) and the sprite (data,mask) index table, extracted from cgagrafx.c of Digger Remastered.
// Copyright (c) Andrew Jenner 1998-2004. License: GNU GPL v2 (see LICENSE).

import { decode } from './b64';

const cgazero60 = decode('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
const cgaediggermask = decode('wAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAD');
const cgardigger1 = decode('AAAAAAAPAAAAP8AAADDAAAAwwAAAMMAAAqqhVQqqpVUqqqUAgqqlVTyoIVXDI8AAwwwwADwMMAAAA8AA');
const cgardigger1mask = decode('//D////AP///AA///wAP//8AD//8AAwA8AAAAMAAAAAAAAAAAAAAAAAAAAAAAAwAAAAD/wDAA//D8A//');
const cgardigger2 = decode('AAAAAAAAAAAADwAAAD/AAAAwwAAAMMBUAqqlVAqqpUAqqqUAqqglQIKjxVQ8jDBUwwwwAMMDwAA8AAAA');
const cgardigger2mask = decode('///////w////wD///wAP//8ADwP8AAAA8AAAAMAAAAMAAAA/AAAAAwAAAAAAAAAAAAADAwAwD/8A/D//');
const cgardigger3 = decode('AAAAAAAAAAAAAAAAAA8AAAA/wFAAMMFQAqqlQAqqpQAqqqUAgqqlADyoJUDDI8FQwwwwUDwMMAAAA8AA');
const cgardigger3mask = decode('////////////8P///8A/D/8ADAP8AAAD8AAAD8AAAD8AAAA/AAAAPwAAAA8AAAADAAAAAwDAAw/D8A//');
const cgarxdigger1 = decode('AAAAAAAAAAAAAAAAAAAAAAAPAAAAP8AAAqqhVQqqpVUqqqUAgqqlVTyoIVXDI8AAwwwwADwMMAAAA8AA');
const cgarxdigger1mask = decode('//////////////////D////AP//8AAwA8AAAAMAAAAAAAAAAAAAAAAAAAAAAAAwAAAAD/wDAA//D8A//');
const cgarxdigger2 = decode('AAAAAAAAAAAAAAAAAAAAAAAPAAAAP8BUAqqlVAqqpUAqqqUAqqglQIKjxVQ8jDBUwwwwAMMDwAA8AAAA');
const cgarxdigger2mask = decode('//////////////////D////APwP8AAAA8AAAAMAAAAMAAAA/AAAAAwAAAAAAAAAAAAADAwAwD/8A/D//');
const cgarxdigger3 = decode('AAAAAAAAAAAAAAAAAAAAAAAPAFAAP8FQAqqlQAqqpQAqqqUAgqqlADyoJUDDI8FQwwwwUDwMMAAAA8AA');
const cgarxdigger3mask = decode('//////////////////D/D//APAP8AAAD8AAAD8AAAD8AAAA/AAAAPwAAAA8AAAADAAAAAwDAAw/D8A//');
const cgaudigger1 = decode('AFFAAABRQAAAUUAAAFFAAAAVAAA8qoAAwyq/wMMqgPA8qoDwAKq/wACqgAAPKoAAMMoAADDIAAAPIAAA');
const cgaudigger1mask = decode('/AAP//wAD//8AA///AAP/8MAP/8AAAA/AAAADwAAAAMAAAADwAAAD/AAAD/AAA//AAA//wAA///AA///');
const cgaudigger2 = decode('AUBQAAFAUAABUVAAAVVQAABVQAAPKoAAMMq/ADDKg8APKoPAACq/AACqgAA8qoAAwyoAAMMoAAA8oAAA');
const cgaudigger2mask = decode('8AwD//AMA//wAAP/8AAD//AAD//AAAD/AAAAPwAAAA/AAAAP8AAAP8AAAP8AAA//AAA//wAD//8AD///');
const cgaudigger3 = decode('AAAAAAUAFAAFQFQAAVVQAABVQAA8qoAAwyq8AMMqjwA8qo8AAKq8AACqgAAPKoAAMMoAADDIAAAPIAAA');
const cgaudigger3mask = decode('8P/D/8A/AP/AAAD/8AAD/8AAD/8AAAP/AAAA/wAAAD8AAAA/wAAA//AAA//AAA//AAA//wAA///AA///');
const cgauxdigger1 = decode('AFFAAABRQAAAUUAAAFFAAAAVAAA8qoAAwyqwAMMqvAA8qrwAAKqwAACqgAAPKoAAMMoAADDIAAAPIAAA');
const cgauxdigger1mask = decode('/AAP//wAD//8AA///AAP/8MAP/8AAA//AAAD/wAAAP8AAAD/wAAD//AAD//AAA//AAA//wAA///AA///');
const cgauxdigger2 = decode('AUBQAAFAUAABUVAAAVVQAABVQAAPKoAAMMqwADDKvAAPKrwAACqwAACqgAA8qoAAwyoAAMMoAAA8oAAA');
const cgauxdigger2mask = decode('8AwD//AMA//wAAP/8AAD//AAD//AAA//AAAD/wAAAP/AAAD/8AAD/8AAD/8AAA//AAA//wAA//8AA///');
const cgauxdigger3 = decode('AAAAAAUAFAAFQFQAAVVQAABVQAA8qoAAwyqwAMMqvAA8qrwAAKqwAACqgAAPKoAAMMoAADDIAAAPIAAA');
const cgauxdigger3mask = decode('8P/D/8A/AP/AAAD/8AAD/8AAD/8AAA//AAAD/wAAAP8AAAD/wAAD//AAD//AAA//AAA//wAA///AA///');
const cgaldigger1 = decode('AAAAAAAA8AAAA/wAAAMMAAADDAAAAwwAVUqqgFVaqqAAWqqoVVqqglVIKjwAA8jDAAwwwwAMMDwAA8AA');
const cgaldigger1mask = decode('//8P///8A///8AD///AA///wAP8AMAA/AAAADwAAAAMAAAAAAAAAAAAAAAAAMAAA/8AAAP/AAwD/8A/D');
const cgaldigger2 = decode('AAAAAAAAAAAAAPAAAAP8AAADDAAVQwwAFVqqgAFaqqAAWqqoAVgqqhVTwoIVTDA8AAwwwwADwMMAAAA8');
const cgaldigger2mask = decode('////////D////AP///AA/8AwAP8AAAA/AAAAD8AAAAP8AAAAwAAAAAAAAAAAAAAAwAAAAP/wDAD//D8A');
const cgaldigger3 = decode('AAAAAAAAAAAAAAAAAADwAAUD/AAFQwwAAVqqgABaqqAAWqqoAFqqggFYKjwFQ8jDBQwwwwAMMDwAA8AA');
const cgaldigger3mask = decode('/////////////w//8PwD/8AwAP/AAAA/8AAAD/wAAAP8AAAA/AAAAPAAAADAAAAAwAAAAPDAAwD/8A/D');
const cgalxdigger1 = decode('AAAAAAAAAAAAAAAAAAAAAAAA8AAAA/wAVUqqgFVaqqAAWqqoVVqqglVIKjwAA8jDAAwwwwAMMDwAA8AA');
const cgalxdigger1mask = decode('//////////////////8P///8A/8AMAA/AAAADwAAAAMAAAAAAAAAAAAAAAAAMAAA/8AAAP/AAwD/8A/D');
const cgalxdigger2 = decode('AAAAAAAAAAAAAAAAAAAAAAAA8AAVQ/wAFVqqgAFaqqAAWqqoAVgqqhVTwoIVTDA8AAwwwwADwMMAAAA8');
const cgalxdigger2mask = decode('//////////////////8P/8A8A/8AAAA/AAAAD8AAAAP8AAAAwAAAAAAAAAAAAAAAwAAAAP/wDAD//D8A');
const cgalxdigger3 = decode('AAAAAAAAAAAAAAAAAAAAAAUA8AAFQ/wAAVqqgABaqqAAWqqoAFqqggFYKjwFQ8jDBQwwwwAMMDwAA8AA');
const cgalxdigger3mask = decode('////////////////8P8P/8A8A//AAAA/8AAAD/wAAAP8AAAA/AAAAPAAAADAAAAAwAAAAPDAAwD/8A/D');
const cgaddigger1 = decode('AAAI8AAAIwwAAKMMAAKo8AACqgAD/qoADwKqPA8CqMMD/qjDAAKqPAAAVAAAAVUAAAFFAAABRQAAAUUA');
const cgaddigger1mask = decode('///AA///AAD//AAA//AAA/wAAA/wAAADwAAAAMAAAADwAAAA/AAAAP/8AMP/8AA///AAP//wAD//8AA/');
const cgaddigger2 = decode('AAAKPAAAKMMAAKjDAAKqPAACqgAA/qgAA8Ko8APCowwA/qMMAAKo8AABVAAABUVAAAUBQAAFAUAABQFA');
const cgaddigger2mask = decode('///AAP//AAD//AAA//AAAP8AAAP8AAAP8AAAA/AAAAD8AAAA/wAAA//wAA//wAAP/8AwD//AMA//wDAP');
const cgaddigger3 = decode('AAAI8AAAIwwAAKMMAAKo8AACqgAAPqoAAPKqPADyqMMAPqjDAAKqPAABVQAABVVAABUBUAAUAFAAAAAA');
const cgaddigger3mask = decode('///AA///AAD//AAA//AAA//AAA//AAAD/AAAAPwAAAD/AAAA/8AAAP/wAAP/wAAP/wAAA/8A/AP/w/8P');
const cgadxdigger1 = decode('AAAI8AAAIwwAAKMMAAKo8AACqgAADqoAAD6qPAA+qMMADqjDAAKqPAAAVAAAAVUAAAFFAAABRQAAAUUA');
const cgadxdigger1mask = decode('///AA///AAD//AAA//AAA//wAA//wAAD/wAAAP8AAAD/wAAA//AAAP/8AMP/8AA///AAP//wAD//8AA/');
const cgadxdigger2 = decode('AAAKPAAAKMMAAKjDAAKqPAACqgAADqgAAD6o8AA+owwADqMMAAKo8AABVAAABUVAAAUBQAAFAUAABQFA');
const cgadxdigger2mask = decode('///AAP//AAD//AAA//AAAP/wAAP/wAAP/wAAA/8AAAD/wAAA//AAA//wAA//wAAP/8AwD//AMA//wDAP');
const cgadxdigger3 = decode('AAAI8AAAIwwAAKMMAAKo8AACqgAADqoAAD6qPAA+qMMADqjDAAKqPAABVQAABVVAABUBUAAUAFAAAAAA');
const cgadxdigger3mask = decode('///AA///AAD//AAA//AAA//wAA//wAAD/wAAAP8AAAD/wAAA//AAAP/wAAP/wAAP/wAAA/8A/AP/w/8P');
const cgadiggerd = decode('AAAAAAADwDwADzD/AA/w8wVDyjxVWCqCUFqqqAVaqqBVSqqAUAMPAAAAzAAAAw8AAAD/AAAAPAAAAAAA');
const cgadiggerdmask = decode('//w/w//wDwD/wAAA8AAAAAAAAAAAAAAAAAAAAAAAAAMAAAAPADAAPw/wAD//8AA///wAP///AP///8P/');
const cgagrave1 = decode('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAAAX9QABf/9QAf//0AAAAAA');
const cgagrave1mask = decode('//////////////////////////////////////////////////A///8AA//wAAA/wAAAD8AAAA8AAAAD');
const cgagrave2 = decode('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUAAAF/UAAX//UAH//9AEA//0BPM/9AAAAAA');
const cgagrave2mask = decode('///////////////////////////////////////wP///AAP/8AAAP8AAAA/AAAAPAAAAAwAAAAMAAAAD');
const cgagrave3 = decode('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVAAABf1AAF//1AB///QBAP/9ATzP/QEAzAEBD8zxAAAAAA');
const cgagrave3mask = decode('////////////////////////////8D///wAD//AAAD/AAAAPwAAADwAAAAMAAAADAAAAAwAAAAMAAAAD');
const cgagrave4 = decode('AAAAAAAAAAAAAAAAAAVAAABf1AAF//1AB///QBAP/9ATzP/QEAzAEBD8zxATPMAQE8zP0B/8z9AAAAAA');
const cgagrave4mask = decode('////////////8D///wAD//AAAD/AAAAPwAAADwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAAD');
const cgagrave5 = decode('AAAAAAAFQAAAX9QABf/9QAf//0AQD//QE8z/0BAMwBAQ/M8QEzzAEBPMz9Af/M/QH//P0B///9Af///Q');
const cgagrave5mask = decode('//A///8AA//wAAA/wAAAD8AAAA8AAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAAD');
const cgarbigger1 = decode('AAAAAAAPAAAAP8AAADDAAAAwwAAAMMAAAVVSqgVVWqoVVVoAQVVaqjxUEqrDE8AAwwwwADwMMAAAA8AA');
const cgarbigger1mask = decode('//D////AP///AA///wAP//8AD//8AAwA8AAAAMAAAAAAAAAAAAAAAAAAAAAAAAwAAAAD/wDAA//D8A//');
const cgarbigger2 = decode('AAAAAAAAAAAADwAAAD/AAAAwwAAAMMCoAVVaqAVVWoAVVVoAVVQagEFTyqg8TDCowwwwAMMDwAA8AAAA');
const cgarbigger2mask = decode('///////w////wD///wAP//8ADwP8AAAA8AAAAMAAAAMAAAA/AAAAAwAAAAAAAAAAAAADAwAwD/8A/D//');
const cgarbigger3 = decode('AAAAAAAAAAAAAAAAAA8AAAA/wKAAMMKgAVVagAVVWgAVVVoAQVVaADxUGoDDE8KgwwwwoDwMMAAAA8AA');
const cgarbigger3mask = decode('////////////8P///8A/D/8ADAP8AAAD8AAAD8AAAD8AAAA/AAAAPwAAAA8AAAADAAAAAwDAAw/D8A//');
const cgarxbigger1 = decode('AAAAAAAAAAAAAAAAAAAAAAAPAAAAP8AAAVVSqgVVWqoVVVoAQVVaqjxUEqrDE8AAwwwwADwMMAAAA8AA');
const cgarxbigger1mask = decode('//////////////////D////AP//8AAwA8AAAAMAAAAAAAAAAAAAAAAAAAAAAAAwAAAAD/wDAA//D8A//');
const cgarxbigger2 = decode('AAAAAAAAAAAAAAAAAAAAAAAPAAAAP8CoAVVaqAVVWoAVVVoAVVQagEFTyqg8TDCowwwwAMMDwAA8AAAA');
const cgarxbigger2mask = decode('//////////////////D////APwP8AAAA8AAAAMAAAAMAAAA/AAAAAwAAAAAAAAAAAAADAwAwD/8A/D//');
const cgarxbigger3 = decode('AAAAAAAAAAAAAAAAAAAAAAAPAKAAP8KgAVVagAVVWgAVVVoAQVVaADxUGoDDE8KgwwwwoDwMMAAAA8AA');
const cgarxbigger3mask = decode('//////////////////D/D//APAP8AAAD8AAAD8AAAD8AAAA/AAAAPwAAAA8AAAADAAAAAwDAAw/D8A//');
const cgaubigger1 = decode('AKKAAACigAAAooAAAKKAAAAqAAA8VUAAwxV/wMMVQPA8VUDwAFV/wABVQAAPFUAAMMUAADDEAAAPEAAA');
const cgaubigger1mask = decode('/AAP//wAD//8AA///AAP/8MAP/8AAAA/AAAADwAAAAMAAAADwAAAD/AAAD/AAA//AAA//wAA///AA///');
const cgaubigger2 = decode('AoCgAAKAoAACoqAAAqqgAACqgAAPFUAAMMV/ADDFQ8APFUPAABV/AABVQAA8VUAAwxUAAMMUAAA8UAAA');
const cgaubigger2mask = decode('8AwD//AMA//wAAP/8AAD//AAD//AAAD/AAAAPwAAAA/AAAAP8AAAP8AAAP8AAA//AAA//wAD//8AD///');
const cgaubigger3 = decode('AAAAAAoAKAAKgKgAAqqgAACqgAA8VUAAwxV8AMMVTwA8VU8AAFV8AABVQAAPFUAAMMUAADDEAAAPEAAA');
const cgaubigger3mask = decode('8P/D/8A/AP/AAAD/8AAD/8AAD/8AAAP/AAAA/wAAAD8AAAA/wAAA//AAA//AAA//AAA//wAA///AA///');
const cgauxbigger1 = decode('AKKAAACigAAAooAAAKKAAAAqAAA8VUAAwxVwAMMVfAA8VXwAAFVwAABVQAAPFUAAMMUAADDEAAAPEAAA');
const cgauxbigger1mask = decode('/AAP//wAD//8AA///AAP/8MAP/8AAA//AAAD/wAAAP8AAAD/wAAD//AAD//AAA//AAA//wAA///AA///');
const cgauxbigger2 = decode('AoCgAAKAoAACoqAAAqqgAACqgAAPFUAAMMVwADDFfAAPFXwAABVwAABVQAA8VUAAwxUAAMMUAAA8UAAA');
const cgauxbigger2mask = decode('8AwD//AMA//wAAP/8AAD//AAD//AAA//AAAD/wAAAP/AAAD/8AAD/8AAD/8AAA//AAA//wAA//8AA///');
const cgauxbigger3 = decode('AAAAAAoAKAAKgKgAAqqgAACqgAA8VUAAwxVwAMMVfAA8VXwAAFVwAABVQAAPFUAAMMUAADDEAAAPEAAA');
const cgauxbigger3mask = decode('8P/D/8A/AP/AAAD/8AAD/8AAD/8AAA//AAAD/wAAAP8AAAD/wAAD//AAD//AAA//AAA//wAA///AA///');
const cgalbigger1 = decode('AAAAAAAA8AAAA/wAAAMMAAADDAAAAwwAqoVVQKqlVVAApVVUqqVVQaqEFTwAA8TDAAwwwwAMMDwAA8AA');
const cgalbigger1mask = decode('//8P///8A///8AD///AA///wAP8AMAA/AAAADwAAAAMAAAAAAAAAAAAAAAAAMAAA/8AAAP/AAwD/8A/D');
const cgalbigger2 = decode('AAAAAAAAAAAAAPAAAAP8AAADDAAqgwwAKqVVQAKlVVAApVVUAqQVVSqjwUEqjDA8AAwwwwADwMMAAAA8');
const cgalbigger2mask = decode('////////D////AP///AA/8AwAP8AAAA/AAAAD8AAAAP8AAAAwAAAAAAAAAAAAAAAwAAAAP/wDAD//D8A');
const cgalbigger3 = decode('AAAAAAAAAAAAAAAAAADwAAoD/AAKgwwAAqVVQAClVVAApVVUAKVVQQKkFTwKg8TDCgwwwwAMMDwAA8AA');
const cgalbigger3mask = decode('/////////////w//8PwD/8AwAP/AAAA/8AAAD/wAAAP8AAAA/AAAAPAAAADAAAAAwAAAAPDAAwD/8A/D');
const cgalxbigger1 = decode('AAAAAAAAAAAAAAAAAAAAAAAA8AAAA/wAqoVVQKqlVVAApVVUqqVVQaqEFTwAA8TDAAwwwwAMMDwAA8AA');
const cgalxbigger1mask = decode('//////////////////8P///8A/8AMAA/AAAADwAAAAMAAAAAAAAAAAAAAAAAMAAA/8AAAP/AAwD/8A/D');
const cgalxbigger2 = decode('AAAAAAAAAAAAAAAAAAAAAAAA8AAqg/wAKqVVQAKlVVAApVVUAqQVVSqjwUEqjDA8AAwwwwADwMMAAAA8');
const cgalxbigger2mask = decode('//////////////////8P/8A8A/8AAAA/AAAAD8AAAAP8AAAAwAAAAAAAAAAAAAAAwAAAAP/wDAD//D8A');
const cgalxbigger3 = decode('AAAAAAAAAAAAAAAAAAAAAAoA8AAKg/wAAqVVQAClVVAApVVUAKVVQQKkFTwKg8TDCgwwwwAMMDwAA8AA');
const cgalxbigger3mask = decode('////////////////8P8P/8A8A//AAAA/8AAAD/wAAAP8AAAA/AAAAPAAAADAAAAAwAAAAPDAAwD/8A/D');
const cgadbigger1 = decode('AAAE8AAAEwwAAFMMAAFU8AABVQAD/VUADwFVPA8BVMMD/VTDAAFVPAAAqAAAAqoAAAKKAAACigAAAooA');
const cgadbigger1mask = decode('///AA///AAD//AAA//AAA/wAAA/wAAADwAAAAMAAAADwAAAA/AAAAP/8AMP/8AA///AAP//wAD//8AA/');
const cgadbigger2 = decode('AAAFPAAAFMMAAFTDAAFVPAABVQAA/VQAA8FU8APBUwwA/VMMAAFU8AACqAAACoqAAAoCgAAKAoAACgKA');
const cgadbigger2mask = decode('///AAP//AAD//AAA//AAAP8AAAP8AAAP8AAAA/AAAAD8AAAA/wAAA//wAA//wAAP/8AwD//AMA//wDAP');
const cgadbigger3 = decode('AAAE8AAAEwwAAFMMAAFU8AABVQAAPVUAAPFVPADxVMMAPVTDAAFVPAACqgAACqqAACoCoAAoAKAAAAAA');
const cgadbigger3mask = decode('///AA///AAD//AAA//AAA//AAA//AAAD/AAAAPwAAAD/AAAA/8AAAP/wAAP/wAAP/wAAA/8A/AP/w/8P');
const cgadxbigger1 = decode('AAAE8AAAEwwAAFMMAAFU8AABVQAADVUAAD1VPAA9VMMADVTDAAFVPAAAqAAAAqoAAAKKAAACigAAAooA');
const cgadxbigger1mask = decode('///AA///AAD//AAA//AAA//wAA//wAAD/wAAAP8AAAD/wAAA//AAAP/8AMP/8AA///AAP//wAD//8AA/');
const cgadxbigger2 = decode('AAAFPAAAFMMAAFTDAAFVPAABVQAADVQAAD1U8AA9UwwADVMMAAFU8AACqAAACoqAAAoCgAAKAoAACgKA');
const cgadxbigger2mask = decode('///AAP//AAD//AAA//AAAP/wAAP/wAAP/wAAA/8AAAD/wAAA//AAA//wAA//wAAP/8AwD//AMA//wDAP');
const cgadxbigger3 = decode('AAAE8AAAEwwAAFMMAAFU8AABVQAADVUAAD1VPAA9VMMADVTDAAFVPAACqgAACqqAACoCoAAoAKAAAAAA');
const cgadxbigger3mask = decode('///AA///AAD//AAA//AAA//wAA//wAAD/wAAAP8AAAD/wAAA//AAAP/wAAP/wAAP/wAAA/8A/AP/w/8P');
const cgabiggerd = decode('AAAAAAADwDwADzD/AA/w8wqDxTyqpBVBoKVVVAqlVVCqhVVAoAMPAAAAzAAAAw8AAAD/AAAAPAAAAAAA');
const cgabiggerdmask = decode('//w/w//wDwD/wAAA8AAAAAAAAAAAAAAAAAAAAAAAAAMAAAAPADAAPw/wAD//8AA///wAP///AP///8P/');
const cgasbag = decode('AAAAAAAP8AAAA8AAAA/wAAD//wAD/D/ADwAA8Dw8P/w8AAA8P/w8PDw8PDw/AAD8D/w/8AD//wAAAAAA');
const cgasbagmask = decode('/8AD///AA///8A///wAA//wAAD/wAAAPwAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAA/AAAA//AAD/');
const cgarbag = decode('AAAAAAA/wAAADwAAAD/AAAD//AAD8P8ADAADwDDw//AwAADwP/Dw8DDw8PA8AAPAD/D/AAD/8AAAAAAA');
const cgarbagmask = decode('/8A///8AD///wD///wAD//wAAP/wAAA/wAAADwAAAAMAAAADAAAAAwAAAAMAAAAPwAAAP/AAAP//AA//');
const cgalbag = decode('AAAAAAAD/AAAAPAAAA/8AAA//wAA/w/AA8AAMA8PD/wPAAAMD/8PDA8PDwwDwAAwAP8PwAAP/AAAAAAA');
const cgalbagmask = decode('//wD///wAP//8AP//8AA//8AAD/8AAAP8AAAA8AAAADAAAAAwAAAAMAAAADwAAAD/AAAD/8AAD//8AP/');
const cgafbag = decode('AAwwAAADwAAAA8AAAA/wAAA//AAA/D8AAwAAwAw8P/AMAAAwD/w8MAw8PDADAADAAPw/AAA//AAAA8AA');
const cgafbagmask = decode('/8AD///wD///8A///8AD//8AAP/8AAA/8AAAD8AAAAPAAAADwAAAA8AAAAPwAAAP/AAAP/8AAP//wAP/');
const cgagold1 = decode('AAAAAAADwAAAD/AAAPPwAAP8zAAP/z8AD/8/wAP8/8AA8P8AAw8AAA/zPAA//P8AP/z/wA/z/8ADzP8A');
const cgagold1mask = decode('//w////wD///AAP//AAD//AAAP/AAAA/wAAAD/AAAA/8AAA/8AAA/8AAAP/AAAA/AAAAD8AAAA/wAAA/');
const cgagold2 = decode('AAAAAAAAAAAAAAAAAAAPAADwP8AD/P/wD/8/8A//D8AD/PMAAPP8AA8P8wA/w8/AP/A/8A/zP/ADz8/A');
const cgagold2mask = decode('//////////////D//w/AP/wDAA/wAAADwAAAA8AAAA/wAAA/8AAA/8AAAD/AAAAPAAAAA8AAAAPwAAAP');
const cgagold3 = decode('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8ADwA/zz/A//PP8P/z8/A/w/AADw/PwPDAP/D/zz/wPz/Pw');
const cgagold3mask = decode('///////////////////////////8P/w/8AwAD8AAAAMAAAAAAAAAAMAAAAPAAAADAAAAAAAAAADAAAAD');
const cganobbin1 = decode('AAAAAAPwD8APDXwwDw18MA/9f/AD9V/AAFQVAAAUFAAChBKACgQQoAoBQKAqgACgqqAAoAAAAqgAAAqq');
const cganobbin1mask = decode('/A/wP/AAAA/AAAADwAAAA8AAAAPwAAAP/AAAP/wAAD/wAAAPwAAAA8AwDAMADDwDAAP8AwAP8AD//8AA');
const cganobbin2 = decode('AAAAAAPwD8AP/X/wDw18MA8NfDAD9V/AAFVVAAAUFAAChBKACgVQoAoBQKAKAACgKoACqKqgCqoAAAAA');
const cganobbin2mask = decode('/A/wP/AAAA/AAAADwAAAA8AAAAPwAAAP/AAAP/wAAD/wAAAPwAAAA8AwDAPAPDwDAD/wAAAPwAAAD/AA');
const cganobbin3 = decode('AAAAAAPwD8AP/X/wDD1w8Aw9cPAD9V/AAFVVAAAVVAAChBKACgVQoAoBQKAKAAKoCgAKqiqAAACqoAAA');
const cganobbin3mask = decode('/A/wP/AAAA/AAAADwAAAA8AAAAPwAAAP/AAAP/wAAD/wAAAPwAAAA8AwDAPAPDAAwD/AAAAP8AAAA///');
const cganobbind = decode('AAAAAAAAAAAAAAAAA/APwAw9fDAMPXwwD/1/8AP1X8AAVBUAABQUAAKEEoAKBBCgKoFCqKqgCqoAAAAA');
const cganobbindmask = decode('///////////8D/A/8AAAD8AAAAPAAAADwAAAA/AAAA/8AAA//AAAP/AAAA/AAAADAAAAAAAAAAAAD/AA');
const cgarhobbin1 = decode('AE/EAAE/8QAFMPEAFTDxQBVPxVAVUBVUBVVqoAFVgAAAVWqgABVVQAACgAAAAoAAAAKAAAAKoAAAKqgA');
const cgarhobbin1mask = decode('/AAA//AAAD/AAAA/AAAADwAAAAMAAAAAwAAAA/AAAA/8AAAD/wAAD//AAD//8A////AP///AA///AAD/');
const cgarhobbin2 = decode('AE/EAAE/8QAFPDFAFTwxUBVPxVQVUBWoBVVqAAFVgAAAVWgAABVWoAACgVAAAoAAAAqgAAAqqAAAAAAA');
const cgarhobbin2mask = decode('/AAA//AAAD/AAAA/AAAADwAAAAMAAAADwAAAD/AAAP/8AAAP/wAAA//AAA//8Aw//8AD//8AAP//wAP/');
const cgarhobbin3 = decode('AE/EAAE8MQAFPDFAFT/xUBVPxWgVUBaABVVoAAFVgAAAVWgAABVWgAACgWAACqAAACqoAAAAAAAAAAAA');
const cgarhobbin3mask = decode('/AAA//AAAD/AAAAPAAAAAwAAAAAAAAADwAAAP/AAA//8AAA//wAAA//AAAP/wAAP/wAA///AA///////');
const cgarhobbind = decode('AAAAAAAAAAAAT8QAATwxAAU8MUAVP/FQFU/FaBVQFoAFVWgAAVWoAABVWoAAFVWoAAqgAAAqqAAAAAAA');
const cgarhobbindmask = decode('//////8AA//8AAD/8AAAP8AAAA8AAAADAAAAAAAAAAPAAAA/8AAD//wAAD//AAAD/8AAA/8AAP//wAP/');
const cgalhobbin1 = decode('ABPxAABP/EAATwxQAU8MVAVT8VQVVAVUCqlVUAACVUAKqVUAAVVUAAACgAAAAoAAAAKAAAAKoAAAKqgA');
const cgalhobbin1mask = decode('/wAAP/wAAA/8AAAD8AAAAMAAAAAAAAAAwAAAA/AAAA/AAAA/8AAA//wAA///8A////AP///AA///AAD/');
const cgalhobbin2 = decode('ABPxAABP/EABTDxQBUw8VBVT8VQqVAVUAKlVUAACVUAAKVUACpVUAAVCgAAAAoAAAAqgAAAqqAAAAAAA');
const cgalhobbin2mask = decode('/wAAP/wAAA/wAAADwAAAAAAAAAAAAAAAwAAAA/8AAA/wAAA/wAAA//AAA//8MA///8AD//8AAP//wAP/');
const cgalhobbin3 = decode('ABPxAABMPEABTDxQBU/8VClT8VQClAVUAClVUAACVUAAKVUAApVUAAlCgAAACqAAACqoAAAAAAAAAAAA');
const cgalhobbin3mask = decode('/wAAP/wAAA/wAAADwAAAAAAAAADAAAAA/AAAA/8AAA/wAAA/8AAA//AAA//8AAP//wAA///AA///////');
const cgalhobbind = decode('AAAAAAAT8QAATDxAAUw8UAVP/FQpU/FUApQFVAApVVAAKlVAAqVVACpVVAAACqAAACqoAAAAAAA=');
const cgalhobbindmask = decode('/8AA//8AAD/8AAAP8AAAA8AAAAAAAAAAwAAAAPwAAAP8AAAP8AAAP8AAAP/wAAP//wAA///AA/8=');
const cgabonus = decode('AABUAAABVQAAAUUAAAUBQAAFAFAAFARRABQBVARRAFABVAKgAqAL6AvoL6orqiqqKqoKqAqoAqACoAAA');
const cgafire1 = decode('A8AsvjvM8/s8/DPMM7AAAA==');
const cgafire1mask = decode('wAMAAAAAAAAAAAAAwAP//w==');
const cgafire2 = decode('C4g8rgrI87qsjqOiI4gAAA==');
const cgafire2mask = decode('wDMAAAADAAAAAAAAzAP//w==');
const cgafire3 = decode('CigjooqKs6gquqOjCogAAA==');
const cgafire3mask = decode('wAMAAAAAAAAAAAAAwAP//w==');
const cgaexp1 = decode('AAAwDA6wAoAOsDAMAAAAAA==');
const cgaexp1mask = decode('D/AAAMAD8A/AAwAAD/D//w==');
const cgaexp2 = decode('wAMwDAggAAAIIDAMwAMAAA==');
const cgaexp2mask = decode('D/ADwMPD88/DwwPAD/D//w==');
const cgaexp3 = decode('gAIwDAAAAAAAADAMgAIAAA==');
const cgaexp3mask = decode('D/ADwM/z///P8wPAD/D//w==');
const cgaback1 = decode('r/+q//rr/r6/6/r6/6+v/qv/6r8=');
const cgaback2 = decode('WlpaWlqWlpaWlqWlpaWllpaWlpY=');
const cgaback3 = decode('r6+vr6/r6+vr6/r6+vr6vr6+vr4=');
const cgaback4 = decode('X/9V//XX/X1/1/X1/19f/Vf/1X8=');
const cgaback5 = decode('r/+q//rX/X1/1/r6/6+v/Vf/1X8=');
const cgaback6 = decode('WlpaWlqWlpaWllpaWlpalpaWlpY=');
const cgaback7 = decode('r6+vr6/X19fX1/X19fX1vr6+vr4=');
const cgaback8 = decode('+vr6+vq+vr6+vq+vr6+vvr6+vr4=');
const cgarightblobmask = decode('8P8A/wA/AA8ADwADAAAAAAAAAAAAAAAAAAMADwA/AD/D/w//');
const cgatopblobmask = decode('///AA/////wAAD////AAAAP//AAAAAA/8AAAAAD//wAAAAAP');
const cgaleftblobmask = decode('//D/APwA8ADwAMAAAAAAAAAAAAAAAAAAwADwAPAA/AD/w/8P');
const cgabottomblobmask = decode('/AAAAAA/8AAAAAD//wAAAAAP/8AAAAP///wAAD/////AA///');
const cgasquareblobmask = decode('8PDw8PD//AAAAAA/8AAAAAD//wAAAAAP/8AAAAA//wAAAAD/');
const cgafurryblobmask = decode('/Dw8PDw/8AAAAAD//wAAAAAP/AAAAAA/8AAAAAD//wAAAAAP/8PDw8P//w8PDw//');
const cgaemerald = decode('AAAAAAAFVUAAF1VQAF1VVAAXVRAABVRAAAFRAAAAVAAAABAAAAAAAA==');
const cgaemeraldmask = decode('/8AAD/8AAAP8AAAA8AAAAPwAAAD/AAAD/8AAD//wAD///AD///8D/w==');
const cgaliferight = decode('AA8AAAA/wAAAMMAAAqqhVQqqpVUqqqUAqqqlVYKoIVU8o8AAwwwwAMMMMAA8A8AA');
const cgaliferightmask = decode('/8A///8AD//8AAwA8AAAAMAAAAAAAAAAAAAAAAAAAAAAAAwAAAAD/wAAA/8A8A//');
const cgalifeleft = decode('AADwAAAD/AAAAwwAVUqqgFVaqqAAWqqoVVqqqlVIKoIAA8o8AAwwwwAMMMMAA8A8');
const cgalifeleftmask = decode('//wD///wAP8AMAA/AAAADwAAAAMAAAAAAAAAAAAAAAAAMAAA/8AAAP/AAAD/8A8A');
const cgaelifemask = decode('wAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAD');
const cgaleftlife = decode('AADwAAAD/AAAAwwAqoVVQKqlVVAApVVUqqVVVaqEFUEAA8U8AAwwwwAMMMMAA8A8');
const cgaleftlifemask = decode('//wD///wAP8AMAA/AAAADwAAAAMAAAAAAAAAAAAAAAAAMAAA/8AAAP/AAAD/8A8A');
const cgafire1b = decode('A8AcfTfM8/c8/DPMM3AAAA==');
const cgafire1bmask = decode('wAMAAAAAAAAAAAAAwAP//w==');
const cgafire2b = decode('B0Q8XQXE83VcTVNRE0QAAA==');
const cgafire2bmask = decode('wDMAAAADAAAAAAAAzAP//w==');
const cgafire3b = decode('BRQTUUVFc1QVdVNTBUQAAA==');
const cgafire3bmask = decode('wAMAAAAAAAAAAAAAwAP//w==');
const cgaexp1b = decode('AAAwDA1wAUANcDAMAAAAAA==');
const cgaexp1bmask = decode('D/AAAMAD8A/AAwAAD/D//w==');
const cgaexp2b = decode('wAMwDAQQAAAEEDAMwAMAAA==');
const cgaexp2bmask = decode('D/ADwMPD88/DwwPAD/D//w==');
const cgaexp3b = decode('QAEwDAAAAAAAADAMQAEAAA==');
const cgaexp3bmask = decode('D/ADwM/z///P8wPAD/D//w==');

export interface SpriteImage {
  data: Uint8Array;
  mask: Uint8Array;
}

export const cgaSprites: SpriteImage[] = [
  { data: cgazero60, mask: cgaediggermask }, // 0
  { data: cgardigger1, mask: cgardigger1mask }, // 1
  { data: cgardigger2, mask: cgardigger2mask }, // 2
  { data: cgardigger3, mask: cgardigger3mask }, // 3
  { data: cgarxdigger1, mask: cgarxdigger1mask }, // 4
  { data: cgarxdigger2, mask: cgarxdigger2mask }, // 5
  { data: cgarxdigger3, mask: cgarxdigger3mask }, // 6
  { data: cgaudigger1, mask: cgaudigger1mask }, // 7
  { data: cgaudigger2, mask: cgaudigger2mask }, // 8
  { data: cgaudigger3, mask: cgaudigger3mask }, // 9
  { data: cgauxdigger1, mask: cgauxdigger1mask }, // 10
  { data: cgauxdigger2, mask: cgauxdigger2mask }, // 11
  { data: cgauxdigger3, mask: cgauxdigger3mask }, // 12
  { data: cgaldigger1, mask: cgaldigger1mask }, // 13
  { data: cgaldigger2, mask: cgaldigger2mask }, // 14
  { data: cgaldigger3, mask: cgaldigger3mask }, // 15
  { data: cgalxdigger1, mask: cgalxdigger1mask }, // 16
  { data: cgalxdigger2, mask: cgalxdigger2mask }, // 17
  { data: cgalxdigger3, mask: cgalxdigger3mask }, // 18
  { data: cgaddigger1, mask: cgaddigger1mask }, // 19
  { data: cgaddigger2, mask: cgaddigger2mask }, // 20
  { data: cgaddigger3, mask: cgaddigger3mask }, // 21
  { data: cgadxdigger1, mask: cgadxdigger1mask }, // 22
  { data: cgadxdigger2, mask: cgadxdigger2mask }, // 23
  { data: cgadxdigger3, mask: cgadxdigger3mask }, // 24
  { data: cgadiggerd, mask: cgadiggerdmask }, // 25
  { data: cgagrave1, mask: cgagrave1mask }, // 26
  { data: cgagrave2, mask: cgagrave2mask }, // 27
  { data: cgagrave3, mask: cgagrave3mask }, // 28
  { data: cgagrave4, mask: cgagrave4mask }, // 29
  { data: cgagrave5, mask: cgagrave5mask }, // 30
  { data: cgazero60, mask: cgaediggermask }, // 31
  { data: cgarbigger1, mask: cgarbigger1mask }, // 32
  { data: cgarbigger2, mask: cgarbigger2mask }, // 33
  { data: cgarbigger3, mask: cgarbigger3mask }, // 34
  { data: cgarxbigger1, mask: cgarxbigger1mask }, // 35
  { data: cgarxbigger2, mask: cgarxbigger2mask }, // 36
  { data: cgarxbigger3, mask: cgarxbigger3mask }, // 37
  { data: cgaubigger1, mask: cgaubigger1mask }, // 38
  { data: cgaubigger2, mask: cgaubigger2mask }, // 39
  { data: cgaubigger3, mask: cgaubigger3mask }, // 40
  { data: cgauxbigger1, mask: cgauxbigger1mask }, // 41
  { data: cgauxbigger2, mask: cgauxbigger2mask }, // 42
  { data: cgauxbigger3, mask: cgauxbigger3mask }, // 43
  { data: cgalbigger1, mask: cgalbigger1mask }, // 44
  { data: cgalbigger2, mask: cgalbigger2mask }, // 45
  { data: cgalbigger3, mask: cgalbigger3mask }, // 46
  { data: cgalxbigger1, mask: cgalxbigger1mask }, // 47
  { data: cgalxbigger2, mask: cgalxbigger2mask }, // 48
  { data: cgalxbigger3, mask: cgalxbigger3mask }, // 49
  { data: cgadbigger1, mask: cgadbigger1mask }, // 50
  { data: cgadbigger2, mask: cgadbigger2mask }, // 51
  { data: cgadbigger3, mask: cgadbigger3mask }, // 52
  { data: cgadxbigger1, mask: cgadxbigger1mask }, // 53
  { data: cgadxbigger2, mask: cgadxbigger2mask }, // 54
  { data: cgadxbigger3, mask: cgadxbigger3mask }, // 55
  { data: cgabiggerd, mask: cgabiggerdmask }, // 56
  { data: cgagrave1, mask: cgagrave1mask }, // 57
  { data: cgagrave2, mask: cgagrave2mask }, // 58
  { data: cgagrave3, mask: cgagrave3mask }, // 59
  { data: cgagrave4, mask: cgagrave4mask }, // 60
  { data: cgagrave5, mask: cgagrave5mask }, // 61
  { data: cgasbag, mask: cgasbagmask }, // 62
  { data: cgarbag, mask: cgarbagmask }, // 63
  { data: cgalbag, mask: cgalbagmask }, // 64
  { data: cgafbag, mask: cgafbagmask }, // 65
  { data: cgagold1, mask: cgagold1mask }, // 66
  { data: cgagold2, mask: cgagold2mask }, // 67
  { data: cgagold3, mask: cgagold3mask }, // 68
  { data: cganobbin1, mask: cganobbin1mask }, // 69
  { data: cganobbin2, mask: cganobbin2mask }, // 70
  { data: cganobbin3, mask: cganobbin3mask }, // 71
  { data: cganobbind, mask: cganobbindmask }, // 72
  { data: cgarhobbin1, mask: cgarhobbin1mask }, // 73
  { data: cgarhobbin2, mask: cgarhobbin2mask }, // 74
  { data: cgarhobbin3, mask: cgarhobbin3mask }, // 75
  { data: cgarhobbind, mask: cgarhobbindmask }, // 76
  { data: cgalhobbin1, mask: cgalhobbin1mask }, // 77
  { data: cgalhobbin2, mask: cgalhobbin2mask }, // 78
  { data: cgalhobbin3, mask: cgalhobbin3mask }, // 79
  { data: cgalhobbind, mask: cgalhobbindmask }, // 80
  { data: cgabonus, mask: cgaediggermask }, // 81
  { data: cgafire1, mask: cgafire1mask }, // 82
  { data: cgafire2, mask: cgafire2mask }, // 83
  { data: cgafire3, mask: cgafire3mask }, // 84
  { data: cgaexp1, mask: cgaexp1mask }, // 85
  { data: cgaexp2, mask: cgaexp2mask }, // 86
  { data: cgaexp3, mask: cgaexp3mask }, // 87
  { data: cgafire1, mask: cgafire1mask }, // 88
  { data: cgafire2, mask: cgafire2mask }, // 89
  { data: cgafire3, mask: cgafire3mask }, // 90
  { data: cgaexp1, mask: cgaexp1mask }, // 91
  { data: cgaexp2, mask: cgaexp2mask }, // 92
  { data: cgaexp3, mask: cgaexp3mask }, // 93
  { data: cgaback1, mask: cgazero60 }, // 94
  { data: cgaback2, mask: cgazero60 }, // 95
  { data: cgaback3, mask: cgazero60 }, // 96
  { data: cgaback4, mask: cgazero60 }, // 97
  { data: cgaback5, mask: cgazero60 }, // 98
  { data: cgaback6, mask: cgazero60 }, // 99
  { data: cgaback7, mask: cgazero60 }, // 100
  { data: cgaback8, mask: cgazero60 }, // 101
  { data: cgazero60, mask: cgarightblobmask }, // 102
  { data: cgazero60, mask: cgatopblobmask }, // 103
  { data: cgazero60, mask: cgaleftblobmask }, // 104
  { data: cgazero60, mask: cgabottomblobmask }, // 105
  { data: cgazero60, mask: cgasquareblobmask }, // 106
  { data: cgazero60, mask: cgafurryblobmask }, // 107
  { data: cgaemerald, mask: cgaemeraldmask }, // 108
  { data: cgazero60, mask: cgaemeraldmask }, // 109
  { data: cgaliferight, mask: cgaliferightmask }, // 110
  { data: cgalifeleft, mask: cgalifeleftmask }, // 111
  { data: cgazero60, mask: cgaelifemask }, // 112
  { data: cgaleftlife, mask: cgaleftlifemask }, // 113
  { data: cgafire1b, mask: cgafire1bmask }, // 114
  { data: cgafire2b, mask: cgafire2bmask }, // 115
  { data: cgafire3b, mask: cgafire3bmask }, // 116
  { data: cgaexp1b, mask: cgaexp1bmask }, // 117
  { data: cgaexp2b, mask: cgaexp2bmask }, // 118
  { data: cgaexp3b, mask: cgaexp3bmask }, // 119
];
